//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assesmant
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int taskid { get; set; }
        public Nullable<int> userid { get; set; }
        public string tasktitle { get; set; }
        public string taskdes { get; set; }
        public string taskstat { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
    
        public virtual user user { get; set; }
    }
}
